CONTAINER Oadvancedikspline
{
    NAME Oadvancedikspline;
    INCLUDE Obase;
    
    GROUP ID_OBJECTPROPERTIES
	{
		LONG ADVANCEDIKSPLINE_MODE
		{
			CYCLE
			{
				ADVANCEDIKSPLINE_MODE_SETUP;
				ADVANCEDIKSPLINE_MODE_BIND;
				ADVANCEDIKSPLINE_MODE_ANIMATE;
			}
			CUSTOMGUI RADIOBUTTONS;
		}
		REAL ADVANCEDIKSPLINE_WIDTH { UNIT METER; MIN 0.0; }
		BOOL ADVANCEDIKSPLINE_REVERSE { }
	}

	GROUP ID_SEGMENTS
	{
        DEFAULT 1;
		LONG ADVANCEDIKSPLINE_SEGMENTS_COUNT { MIN 1; MAXSLIDER 10; CUSTOMGUI LONGSLIDER; }
		LONG ADVANCEDIKSPLINE_SEGMENTS_SUBDIVISIONS_COUNT { MIN 1; MAXSLIDER 10; CUSTOMGUI LONGSLIDER; }
		REAL ADVANCEDIKSPLINE_SEGMENTS_MAIN_CONTROLLER_SIZE { UNIT METER; MIN 0.0; }
		REAL ADVANCEDIKSPLINE_SEGMENTS_INTERMEDIATE_CONTROLLER_SIZE { UNIT METER; MIN 0.0; }
	}
}